### ISSUE TITLE
Call of inherited constructor creates object or the parent type

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/jooc-legacy#60]
ooc code:<pre>
A: class {
    msg: String
    init: func (=msg) {}
}

B: class extends A {
    init: func ~noarg {}
    greet: func {
        msg println()
    }
}

main: func {
    b: B = B new("hey")
    b greet()
}
</pre>

gdb output: <pre>(gdb) bt
#0  0x00000004 in ?? ()
#1  0x080498b0 in B_greet ()
#2  0x0804990c in main ()

</pre>

C code: <pre>B *b = A_new("hey");
    B_greet(b);</pre>

That should be a B object, rather ;)

**Comment by fredreichbier** [comment]
Possibly the same as #59 ;)
